from pathlib import Path

path = Path('/home/ubuntu/KwikDrop/src/App.jsx')
text = path.read_text()
text = text.replace('function Home({go})', 'function Home()')
text = text.replace("<button className=\"button button-primary\" onClick={()=>go('shop')}>See what’s in store <ArrowRight size={17}/></button>", "<a className=\"button button-primary\" href={routeHref('shop')}>See what’s in store <ArrowRight size={17}/></a>")
text = text.replace("<button className=\"hero-link\" onClick={()=>go('how-it-works')}>How ordering works <ArrowUpRight size={15}/></button>", "<a className=\"hero-link\" href={routeHref('how-it-works')}>How ordering works <ArrowUpRight size={15}/></a>")
text = text.replace("<button className=\"button button-secondary\" onClick={()=>go('shop')}>See what’s in the shop <ArrowRight size={16}/></button>", "<a className=\"button button-secondary\" href={routeHref('shop')}>See what’s in the shop <ArrowRight size={16}/></a>")
text = text.replace("<button className=\"under-link\" onClick={()=>go('shop')}>View all products <ArrowUpRight size={15}/></button>", "<a className=\"under-link\" href={routeHref('shop')}>View all products <ArrowUpRight size={15}/></a>")
text = text.replace('function ProductCard({product,index,openProduct}) { return <article className="product-card" onClick={()=>openProduct(product)}>', 'function ProductCard({product,index}) { return <a className="product-card" href={routeHref(`product/${product.id}`)}>')
text = text.replace('<button aria-label={`Open ${product.name}`}><ArrowUpRight size={18}/></button>', '<span className="card-open" aria-hidden="true"><ArrowUpRight size={18}/></span>')
text = text.replace('</div><div className="card-order-hint">See product details <ArrowRight size={14}/></div></article>; }', '</div><div className="card-order-hint">See product details <ArrowRight size={14}/></div></a>; }')
text = text.replace('function InfoPage({type,go})', 'function InfoPage({type})')
text = text.replace("<button className=\"button button-primary\" onClick={()=>go('shop')}>Go to the shop <ArrowRight size={17}/></button>", "<a className=\"button button-primary\" href={routeHref('shop')}>Go to the shop <ArrowRight size={17}/></a>")
text = text.replace("<InfoPage type=\"how\" go={go}/>", "<InfoPage type=\"how\"/>")
text = text.replace("<InfoPage type=\"delivery\" go={go}/>", "<InfoPage type=\"delivery\"/>")
text = text.replace("<InfoPage type=\"faqs\" go={go}/>", "<InfoPage type=\"faqs\"/>")
text = text.replace('<button className="brand footer-logo" onClick={()=>go(\'\')}><span>kwik</span><i>drop</i><b>.</b></button>', '<a className="brand footer-logo" href={routeHref(\'\')}><span>kwik</span><i>drop</i><b>.</b></a>')
text = text.replace("<button onClick={()=>go('shop')}>Shop products <ArrowRight size={14}/></button>", "<a href={routeHref('shop')}>Shop products <ArrowRight size={14}/></a>")
path.write_text(text)
