from pathlib import Path
import re

app = Path('/home/ubuntu/KwikDrop/src/App.jsx')
text = app.read_text()
new_products = r'''const products = [
  { id:'mh150-earbuds', name:'MH150 Wireless Earbuds', category:'Tech', price:199, label:'Wireless audio', intro:'Pocket-sized sound with a checkered charging case.', description:'The supplier’s MH150 true-wireless earbuds with a compact charging case. Colour availability is confirmed with you before delivery; the packaging shows ICASA approval on the rear.', features:['Wireless in-ear design','Charging case included','ICASA-marked packaging'], image:'/products/IMG-20260921-WA0358.jpg', thumbs:['/products/IMG-20260921-WA0358.jpg','/products/IMG-20260921-WA0367.jpg','/products/IMG-20260921-WA0364.jpg'] },
  { id:'power-bank-10000', name:'10,000mAh LED Power Bank', category:'Tech', price:299, label:'Everyday tech', intro:'Visible battery level, multiple USB outputs.', description:'A practical 10,000mAh power bank with a percentage-style LED indicator and multiple USB outputs. A strong everyday carry for phones, commutes and long days out.', features:['10,000mAh capacity','LED battery indicator','Multiple USB outputs'], image:'/products/IMG-20260921-WA0359.jpg', thumbs:['/products/IMG-20260921-WA0359.jpg','/products/IMG-20260921-WA0384.jpg'] },
  { id:'desktop-vacuum-k6', name:'K-6 Desktop Vacuum', category:'Home', price:299, label:'Desk reset', intro:'Small, cordless cleaning for keyboards and workspaces.', description:'The compact K-6 capsule-style vacuum from the supplier range. Designed for quick clean-ups around keyboards, desks and small hard-to-reach spaces.', features:['Compact capsule design','Keyboard-friendly cleaning','Portable everyday format'], image:'/products/IMG-20260921-WA0361.jpg', thumbs:['/products/IMG-20260921-WA0361.jpg','/products/IMG-20260921-WA0416.jpg'] },
  { id:'h009-earbuds', name:'MOBOMART H009 Earbuds', category:'Tech', price:169, label:'Bluetooth 5.3', intro:'True wireless earbuds with a digital case display.', description:'The supplier’s MOBOMART H009 true-wireless headset, marked Bluetooth 5.3 with a digital battery display on the charging case. Exact colour and availability are confirmed before delivery.', features:['Bluetooth 5.3','Digital battery display','True wireless stereo'], image:'/products/IMG-20260921-WA0366.jpg', thumbs:['/products/IMG-20260921-WA0366.jpg','/products/IMG-20260921-WA0421.jpg'] },
  { id:'p9-headphones', name:'P9 Wireless Headphones', category:'Tech', price:199, label:'Over-ear audio', intro:'A bold over-ear Bluetooth pair for music on the move.', description:'Supplier-stock P9 / YJ-45 style over-ear Bluetooth headphones. The box shows multiple colour options; we confirm the available colour with you before delivery.', features:['Over-ear fit','Bluetooth wireless audio','Multiple colours may be available'], image:'/products/IMG-20260921-WA0368.jpg', thumbs:['/products/IMG-20260921-WA0368.jpg','/products/IMG-20260921-WA0370.jpg'] },
  { id:'pro5s-earbuds', name:'Pro 5s Wireless Earbuds', category:'Tech', price:199, label:'Popular pick', intro:'AirPods-style true wireless earbuds for everyday listening.', description:'A clean, compact Pro 5s true-wireless design from the supplier range. Ask us about the colour currently available before placing your order.', features:['True wireless stereo','Compact charging case','AirPods-style fit'], image:'/products/IMG-20260921-WA0371.jpg', thumbs:['/products/IMG-20260921-WA0371.jpg','/products/IMG-20260921-WA0358.jpg'] },
  { id:'mosquito-trap-lamp', name:'365nm Mosquito Trap Lamp', category:'Home', price:249, label:'Home comfort', intro:'Compact UV light trap for indoor spaces.', description:'A compact photo-catalytic mosquito trap lamp with a 365nm light wave, available in black or white depending on current stock. We confirm the exact unit before delivery.', features:['365nm UV light','Compact cylindrical form','Black or white stock may vary'], image:'/products/IMG-20260921-WA0369.jpg', thumbs:['/products/IMG-20260921-WA0369.jpg','/products/IMG-20260921-WA0408.jpg','/products/IMG-20260921-WA0378.jpg'] },
  { id:'motivational-bottle-2l', name:'2L Motivational Water Bottle', category:'Everyday', price:149, label:'Hydration pick', intro:'A bright gradient bottle with time markers and a straw.', description:'A 2L gradient motivational bottle with hydration time markers, a flip-top lid and straw. Colour is selected from the available supplier stock.', features:['2L capacity','Time-marker design','Straw and flip-top lid'], image:'/products/IMG-20260921-WA0382.jpg', thumbs:['/products/IMG-20260921-WA0382.jpg','/products/IMG-20260921-WA0412.jpg','/products/IMG-20260921-WA0375.jpg'] },
  { id:'afrihome-tumbler-1200', name:'Afrihome 1200ml Steel Tumbler', category:'Everyday', price:299, label:'Daily carry', intro:'A large handled stainless-steel tumbler with straw.', description:'The supplier’s Afrihome Choice 1200ml food-grade 304 stainless-steel cup, with a handled lid and straw. A substantial everyday drinkware option.', features:['1200ml capacity','304 stainless steel','Handle and straw included'], image:'/products/IMG-20260921-WA0387.jpg', thumbs:['/products/IMG-20260921-WA0387.jpg','/products/IMG-20260921-WA0389.jpg','/products/IMG-20260921-WA0392.jpg'] },
  { id:'vacuum-coffee-mug', name:'Stainless Steel Vacuum Mug', category:'Everyday', price:179, label:'Daily carry', intro:'A warm-drink companion with a lid and carry strap.', description:'A stainless-steel vacuum coffee mug from the supplier range, with a flip-top lid and fabric carry strap. Stock may include cream or black.', features:['Vacuum insulated body','Flip-top lid','Carry strap'], image:'/products/IMG-20260921-WA0399.jpg', thumbs:['/products/IMG-20260921-WA0399.jpg','/products/IMG-20260921-WA0396.jpg'] },
  { id:'smart-temperature-mug', name:'Smart Temperature Display Mug', category:'Everyday', price:199, label:'Smart everyday', intro:'Vacuum insulation with a touch temperature display.', description:'A stainless-steel vacuum mug with a digital temperature display on the lid. The supplier packaging describes hot-and-cold retention; colour and stock are confirmed before delivery.', features:['Digital temperature display','Vacuum insulated','Stainless-steel body'], image:'/products/IMG-20260921-WA0406.jpg', thumbs:['/products/IMG-20260921-WA0406.jpg','/products/IMG-20260921-WA0402.jpg'] },
  { id:'ultrapods-max', name:'Ultrapods Max Earbuds', category:'Tech', price:199, label:'Bluetooth 5.3', intro:'Hi-Res wireless earbuds with an LED charging case.', description:'Supplier-stock Ultrapods Max earbuds marked Bluetooth 5.3, Hi-Res sound and an LED digital display case. Available colour depends on current stock.', features:['Bluetooth 5.3','LED digital display case','Water-resistant design marked IPX4'], image:'/products/IMG-20260921-WA0404.jpg', thumbs:['/products/IMG-20260921-WA0404.jpg','/products/IMG-20260921-WA0410.jpg'] },
  { id:'rabbit-fan', name:'Rabbit Mini Fan', category:'Home', price:99, label:'Cool-down pick', intro:'A playful portable fan with three speed settings.', description:'The supplier’s Rabbit Fan / RF60 style portable fan. The packaging shows a compact USB-charged, three-speed design; colour and stock are confirmed with you before delivery.', features:['Three speed settings','USB rechargeable','Compact rabbit design'], image:'/products/IMG-20260921-WA0394.jpg', thumbs:['/products/IMG-20260921-WA0394.jpg','/products/IMG-20260921-WA0388.jpg','/products/IMG-20260921-WA0414.jpg'] },
  { id:'wooden-hair-brush', name:'Wooden Hair Brush', category:'Everyday', price:59, label:'Self-care', intro:'Simple round and paddle brushes for everyday grooming.', description:'Assorted wooden-handle round and paddle hair brushes from the supplier display. Shape and colour are selected from the available stock.', features:['Wooden handles','Round and paddle styles','Everyday grooming essential'], image:'/products/IMG-20260921-WA0360.jpg', thumbs:['/products/IMG-20260921-WA0360.jpg'] }
];'''
text = re.sub(r"const products = \[.*?\n\s*\];", new_products, text, count=1, flags=re.S)
app.write_text(text)
print('updated', app)
