import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, ArrowUpRight, BadgeCheck, ChevronDown, ChevronLeft, Heart, Menu, MessageCircle, Search, ShieldCheck, Truck, X, MapPin, Clock3, CheckCircle2 } from 'lucide-react';

const WHATSAPP_NUMBER = '27821234567';
const money = (value) => `R${value.toLocaleString('en-ZA')}`;
const chatUrl = (message) => `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
const routeHref = (hash='') => `${window.location.pathname}${hash ? `#${hash}` : ''}`;
const categories = ['All products','Tech','Home','Everyday'];
const products = [
  { id:'mh150-earbuds', name:'MH150 Wireless Earbuds', category:'Tech', price:199, label:'Wireless audio', intro:'Pocket-sized sound with a checkered charging case.', description:'The supplier’s MH150 true-wireless earbuds with a compact charging case. Colour availability is confirmed with you before delivery; the packaging shows ICASA approval on the rear.', features:['Wireless in-ear design','Charging case included','ICASA-marked packaging'], image:'/products/IMG-20260921-WA0358.jpg', thumbs:['/products/IMG-20260921-WA0358.jpg','/products/IMG-20260921-WA0367.jpg','/products/IMG-20260921-WA0364.jpg'] },
  { id:'power-bank-10000', name:'10,000mAh LED Power Bank', category:'Tech', price:299, label:'Everyday tech', intro:'Visible battery level, multiple USB outputs.', description:'A practical 10,000mAh power bank with a percentage-style LED indicator and multiple USB outputs. A strong everyday carry for phones, commutes and long days out.', features:['10,000mAh capacity','LED battery indicator','Multiple USB outputs'], image:'/products/IMG-20260921-WA0359.jpg', thumbs:['/products/IMG-20260921-WA0359.jpg','/products/IMG-20260921-WA0384.jpg'] },
  { id:'desktop-vacuum-k6', name:'K-6 Desktop Vacuum', category:'Home', price:299, label:'Desk reset', intro:'Small, cordless cleaning for keyboards and workspaces.', description:'The compact K-6 capsule-style vacuum from the supplier range. Designed for quick clean-ups around keyboards, desks and small hard-to-reach spaces.', features:['Compact capsule design','Keyboard-friendly cleaning','Portable everyday format'], image:'/products/IMG-20260921-WA0361.jpg', thumbs:['/products/IMG-20260921-WA0361.jpg','/products/IMG-20260921-WA0416.jpg'] },
  { id:'h009-earbuds', name:'MOBOMART H009 Earbuds', category:'Tech', price:169, label:'Bluetooth 5.3', intro:'True wireless earbuds with a digital case display.', description:'The supplier’s MOBOMART H009 true-wireless headset, marked Bluetooth 5.3 with a digital battery display on the charging case. Exact colour and availability are confirmed before delivery.', features:['Bluetooth 5.3','Digital battery display','True wireless stereo'], image:'/products/IMG-20260921-WA0366.jpg', thumbs:['/products/IMG-20260921-WA0366.jpg','/products/IMG-20260921-WA0421.jpg'] },
  { id:'p9-headphones', name:'P9 Wireless Headphones', category:'Tech', price:199, label:'Over-ear audio', intro:'A bold over-ear Bluetooth pair for music on the move.', description:'Supplier-stock P9 / YJ-45 style over-ear Bluetooth headphones. The box shows multiple colour options; we confirm the available colour with you before delivery.', features:['Over-ear fit','Bluetooth wireless audio','Multiple colours may be available'], image:'/products/IMG-20260921-WA0368.jpg', thumbs:['/products/IMG-20260921-WA0368.jpg','/products/IMG-20260921-WA0370.jpg'] },
  { id:'pro5s-earbuds', name:'Pro 5s Wireless Earbuds', category:'Tech', price:199, label:'Popular pick', intro:'AirPods-style true wireless earbuds for everyday listening.', description:'A clean, compact Pro 5s true-wireless design from the supplier range. Ask us about the colour currently available before placing your order.', features:['True wireless stereo','Compact charging case','AirPods-style fit'], image:'/products/IMG-20260921-WA0371.jpg', thumbs:['/products/IMG-20260921-WA0371.jpg','/products/IMG-20260921-WA0358.jpg'] },
  { id:'mosquito-trap-lamp', name:'365nm Mosquito Trap Lamp', category:'Home', price:249, label:'Home comfort', intro:'Compact UV light trap for indoor spaces.', description:'A compact photo-catalytic mosquito trap lamp with a 365nm light wave, available in black or white depending on current stock. We confirm the exact unit before delivery.', features:['365nm UV light','Compact cylindrical form','Black or white stock may vary'], image:'/products/IMG-20260921-WA0369.jpg', thumbs:['/products/IMG-20260921-WA0369.jpg','/products/IMG-20260921-WA0408.jpg','/products/IMG-20260921-WA0378.jpg'] },
  { id:'motivational-bottle-2l', name:'2L Motivational Water Bottle', category:'Everyday', price:149, label:'Hydration pick', intro:'A bright gradient bottle with time markers and a straw.', description:'A 2L gradient motivational bottle with hydration time markers, a flip-top lid and straw. Colour is selected from the available supplier stock.', features:['2L capacity','Time-marker design','Straw and flip-top lid'], image:'/products/IMG-20260921-WA0382.jpg', thumbs:['/products/IMG-20260921-WA0382.jpg','/products/IMG-20260921-WA0412.jpg','/products/IMG-20260921-WA0375.jpg'] },
  { id:'afrihome-tumbler-1200', name:'Afrihome 1200ml Steel Tumbler', category:'Everyday', price:299, label:'Daily carry', intro:'A large handled stainless-steel tumbler with straw.', description:'The supplier’s Afrihome Choice 1200ml food-grade 304 stainless-steel cup, with a handled lid and straw. A substantial everyday drinkware option.', features:['1200ml capacity','304 stainless steel','Handle and straw included'], image:'/products/IMG-20260921-WA0387.jpg', thumbs:['/products/IMG-20260921-WA0387.jpg','/products/IMG-20260921-WA0389.jpg','/products/IMG-20260921-WA0392.jpg'] },
  { id:'vacuum-coffee-mug', name:'Stainless Steel Vacuum Mug', category:'Everyday', price:179, label:'Daily carry', intro:'A warm-drink companion with a lid and carry strap.', description:'A stainless-steel vacuum coffee mug from the supplier range, with a flip-top lid and fabric carry strap. Stock may include cream or black.', features:['Vacuum insulated body','Flip-top lid','Carry strap'], image:'/products/IMG-20260921-WA0399.jpg', thumbs:['/products/IMG-20260921-WA0399.jpg','/products/IMG-20260921-WA0396.jpg'] },
  { id:'smart-temperature-mug', name:'Smart Temperature Display Mug', category:'Everyday', price:199, label:'Smart everyday', intro:'Vacuum insulation with a touch temperature display.', description:'A stainless-steel vacuum mug with a digital temperature display on the lid. The supplier packaging describes hot-and-cold retention; colour and stock are confirmed before delivery.', features:['Digital temperature display','Vacuum insulated','Stainless-steel body'], image:'/products/IMG-20260921-WA0406.jpg', thumbs:['/products/IMG-20260921-WA0406.jpg','/products/IMG-20260921-WA0402.jpg'] },
  { id:'ultrapods-max', name:'Ultrapods Max Earbuds', category:'Tech', price:199, label:'Bluetooth 5.3', intro:'Hi-Res wireless earbuds with an LED charging case.', description:'Supplier-stock Ultrapods Max earbuds marked Bluetooth 5.3, Hi-Res sound and an LED digital display case. Available colour depends on current stock.', features:['Bluetooth 5.3','LED digital display case','Water-resistant design marked IPX4'], image:'/products/IMG-20260921-WA0404.jpg', thumbs:['/products/IMG-20260921-WA0404.jpg','/products/IMG-20260921-WA0410.jpg'] },
  { id:'rabbit-fan', name:'Rabbit Mini Fan', category:'Home', price:99, label:'Cool-down pick', intro:'A playful portable fan with three speed settings.', description:'The supplier’s Rabbit Fan / RF60 style portable fan. The packaging shows a compact USB-charged, three-speed design; colour and stock are confirmed with you before delivery.', features:['Three speed settings','USB rechargeable','Compact rabbit design'], image:'/products/IMG-20260921-WA0394.jpg', thumbs:['/products/IMG-20260921-WA0394.jpg','/products/IMG-20260921-WA0388.jpg','/products/IMG-20260921-WA0414.jpg'] },
  { id:'wooden-hair-brush', name:'Wooden Hair Brush', category:'Everyday', price:59, label:'Self-care', intro:'Simple round and paddle brushes for everyday grooming.', description:'Assorted wooden-handle round and paddle hair brushes from the supplier display. Shape and colour are selected from the available stock.', features:['Wooden handles','Round and paddle styles','Everyday grooming essential'], image:'/products/IMG-20260921-WA0360.jpg', thumbs:['/products/IMG-20260921-WA0360.jpg'] }
];

function Reveal({ children, className='' }) { useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold:.12 }); document.querySelectorAll('.reveal').forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, []); return <div className={`reveal ${className}`}>{children}</div>; }

export default function App() {
  const [route,setRoute] = useState(window.location.hash);
  const [menuOpen,setMenuOpen] = useState(false);
  const [searchOpen,setSearchOpen] = useState(false);
  const [query,setQuery] = useState('');
  const [category,setCategory] = useState('All products');
  const [orderProduct,setOrderProduct] = useState(null);
  useEffect(() => { const handler=()=>setRoute(window.location.hash); window.addEventListener('hashchange',handler); return()=>window.removeEventListener('hashchange',handler); },[]);
  useEffect(() => { const handler=(event) => { const anchor=event.target.closest?.('a[href]'); if (!anchor) return; const url=new URL(anchor.href, window.location.href); if (url.origin !== window.location.origin || !url.hash) return; event.preventDefault(); window.history.pushState({},'',`${window.location.pathname}${url.hash}`); setRoute(url.hash); setMenuOpen(false); setSearchOpen(false); }; document.addEventListener('click',handler); return()=>document.removeEventListener('click',handler); },[]);
  useEffect(() => { window.scrollTo({ top:0, behavior:'instant' }); },[route]);
  const go = (hash='') => { const next = hash ? `#${hash}` : ''; setMenuOpen(false); setSearchOpen(false); window.history.pushState({},'',`${window.location.pathname}${next}`); setRoute(next); };
  const currentProduct = route.startsWith('#product/') ? products.find((p)=>p.id===route.slice(9)) : null;
  const requestedPage = route.slice(1) || 'home';
  const page = currentProduct ? 'product' : (requestedPage.startsWith('product/') ? 'shop' : requestedPage);
  const visibleProducts = useMemo(() => products.filter((p)=>(category==='All products'||p.category===category)&&(!query||`${p.name} ${p.intro} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
  return <div className="app-shell"><div className="announcement"><span className="pulse"/> Free delivery <b>Umbilo + Glenwood</b><span>•</span> Pay when it arrives <ArrowUpRight size={13}/></div><header className="site-header"><button className="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen?<X/>:<Menu/>}</button><a className="brand" href={routeHref('')} aria-label="KwikDrop home"><span>kwik</span><i>drop</i><b>.</b></a><nav className={menuOpen?'nav-links open':'nav-links'}><a href={routeHref('')}>Home</a><a href={routeHref('shop')}>Shop</a><a href={routeHref('how-it-works')}>How it works</a><a href={routeHref('delivery')}>Delivery</a><a href={routeHref('faqs')}>FAQs</a></nav><div className="header-actions"><button className="search-trigger" onClick={()=>setSearchOpen(!searchOpen)} aria-label="Search"><Search size={18}/></button><a className="header-chat" href={chatUrl('Hi KwikDrop! I have a question before ordering.')} target="_blank" rel="noreferrer"><MessageCircle size={17}/><span>WhatsApp us</span></a></div></header>{searchOpen&&<div className="searchbar"><Search size={17}/><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search products"/><button onClick={()=>setSearchOpen(false)} aria-label="Close search"><X size={17}/></button></div>}{page==='home'?<Home go={go}/>:page==='shop'?<Shop items={visibleProducts} category={category} setCategory={setCategory} openProduct={(p)=>go(`product/${p.id}`)}/>:page==='how-it-works'?<InfoPage type="how"/>:page==='delivery'?<InfoPage type="delivery"/>:page==='faqs'?<InfoPage type="faqs"/>:<ProductView product={currentProduct} onOrder={()=>setOrderProduct(currentProduct)}/>}<a className="floating-wa" href={chatUrl('Hi KwikDrop! I would like help choosing a product.')} target="_blank" rel="noreferrer"><MessageCircle size={20}/><span>Chat with us</span></a><footer className="site-footer"><div><a className="brand footer-logo" href={routeHref('')}><span>kwik</span><i>drop</i><b>.</b></a><p>Local products. Straightforward service.</p></div><div className="footer-links"><span>Durban, South Africa</span><span>© 2026 KwikDrop</span><a href={routeHref('shop')}>Shop products <ArrowRight size={14}/></a></div></footer>{orderProduct&&<OrderModal product={orderProduct} onClose={()=>setOrderProduct(null)}/>}</div>;
}

function Home() { return <main className="home-page"><section className="hero-cinematic"><div className="hero-bg"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light"><span className="eyebrow-mark"/> Durban’s find-it-first store</div><h1>Good finds.<br/><em>Right around here.</em></h1><p>Tech, home and everyday products worth knowing about — brought to you locally, with a real person on the other side.</p><div className="hero-actions"><a className="button button-primary" href={routeHref('shop')}>See what’s in store <ArrowRight size={17}/></a><a className="hero-link" href={routeHref('how-it-works')}>How ordering works <ArrowUpRight size={15}/></a></div><div className="hero-proof light"><span><CheckCircle2 size={16}/> Stock checked before delivery</span><span><ShieldCheck size={16}/> Pay when it arrives</span></div></div><div className="hero-product-card"><span>THE NEXT DROP</span><strong>Wireless earbuds</strong><small>Ask us when they land.</small></div><div className="hero-scroll">Scroll to explore <ArrowDownIcon/></div></section><Reveal><section className="home-intro"><div className="eyebrow">A store that keeps it moving</div><h2>See it. Ask about it.<br/><em>Get it delivered.</em></h2><p>New products come and go. The standard stays the same: clear prices, honest availability and a real conversation before delivery.</p><a className="button button-secondary" href={routeHref('shop')}>See what’s in the shop <ArrowRight size={16}/></a></section></Reveal><Reveal><section className="home-featured"><div className="section-head"><div><div className="eyebrow">A few things in store</div><h2>Start here.</h2></div><a className="under-link" href={routeHref('shop')}>View all products <ArrowUpRight size={15}/></a></div><div className="featured-grid">{products.slice(0,3).map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={(item)=>go(`product/${item.id}`)}/>)}</div></section></Reveal><Reveal><section className="source-banner"><div><div className="eyebrow">Can’t find what you’re after?</div><h2>Send us the product.<br/><em>We’ll check.</em></h2></div><a className="button button-primary" href={chatUrl('Hi KwikDrop! I am looking for a product I saw online. Can you check availability and price?')} target="_blank" rel="noreferrer">Ask us to source it <MessageCircle size={17}/></a></section></Reveal></main>; }

function Shop({items,category,setCategory,openProduct}) { return <main className="shop-page"><section className="catalog catalog-premium catalog-direct"><div className="catalog-topline"><div><span className="catalog-kicker">The KwikDrop shop</span><h2>Pick your lane.</h2></div><span className="catalog-count-large">{items.length} <small>available now</small></span></div><div className="catalog-head"><span><b>{items.length}</b> products <small>• Free delivery • Pay on delivery</small></span><div className="filter-row">{categories.map((item)=><button className={category===item?'active':''} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</div></div><div className="product-grid product-grid-premium">{items.map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={openProduct}/>)}</div><div className="shop-bottom-note"><div><span className="eyebrow">Looking for something specific?</span><h3>Send us a screenshot. We’ll check it.</h3></div><a href={chatUrl('Hi KwikDrop! I am looking for a product I saw online. Can you check availability and price?')} target="_blank" rel="noreferrer" className="button button-secondary">Ask us to source it <MessageCircle size={16}/></a></div></section></main>; }

function ProductCard({product,index}) { return <a className="product-card" href={routeHref(`product/${product.id}`)}><div className="product-image"><img src={product.image} alt={product.name} loading={index>1?'lazy':'eager'}/><span>{product.label}</span><span className="card-open" aria-hidden="true"><ArrowUpRight size={18}/></span></div><div className="product-card-info"><div><h3>{product.name}</h3><p>{product.category} · {product.intro}</p></div><strong>{money(product.price)}</strong></div><div className="card-order-hint">See product details <ArrowRight size={14}/></div></a>; }

function InfoPage({type}) { const content={how:{eyebrow:'How it works',title:<>Order without<br/><em>the awkward checkout.</em></>,lead:'You choose the product. We confirm the details with you. Then we bring it over and you pay when it arrives.',cards:[['01','Pick a product','Browse the shop and open anything you want to know more about.'],['02','Send the details','Fill in the short form. WhatsApp opens with one complete order message.'],['03','We confirm','We check stock, your area, the the plan with you. Delivery is free in our starting area.'],['04','Receive and pay','We deliver locally. You pay on delivery.']]},delivery:{eyebrow:'Delivery',title:<>Know where we<br/><em>can bring it.</em></>,lead:'KwikDrop is starting close to home so we can keep the service personal and the communication clear.',cards:[['AREA','Umbilo + Glenwood','This is our initial delivery area in Durban. Nearby suburbs may be possible — ask us before ordering.'],['FEE','Confirmed first','Delivery is free in our starting area. We confirm stock and timing with you on WhatsApp before dispatch.'],['PAY','On delivery','There is no card checkout on the website. You pay when your order arrives.'],['TIME','Arranged together','We agree on a suitable delivery time in the WhatsApp conversation.']]},faqs:{eyebrow:'FAQs',title:<>The useful answers,<br/><em>before you ask.</em></>,lead:'No hidden checkout steps. Free delivery in our starting area.',cards:[['How do I order?','Choose a product, complete the short form and continue to WhatsApp.'],['When do I pay?','When the order arrives. We confirm the product and delivery details first.'],['Can you find another product?','Send us the product name, link or a photo. We’ll check availability and price.'],['Do you deliver outside the starting area?','Message us with your suburb. Nearby delivery may be possible depending on the order.']]}}[type]; return <main className="info-page"><section className="page-hero"><div className="eyebrow"><span className="eyebrow-mark"/> {content.eyebrow}</div><h1>{content.title}</h1><p>{content.lead}</p></section><Reveal><section className={`info-grid ${type==='faqs'?'faq-grid':''}`}>{content.cards.map((card)=><div className="info-card" key={card[0]}>{type==='faqs'?<><h3>{card[0]} <ChevronDown size={17}/></h3><p>{card[1]}</p></>:<><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></>}</div>)}</section></Reveal><div className="info-cta"><h2>Ready to look around?</h2><a className="button button-primary" href={routeHref('shop')}>Go to the shop <ArrowRight size={17}/></a></div></main>; }

function ArrowDownIcon(){return <span className="arrow-down">↓</span>}
function ProductView({product,onOrder}) { const [image,setImage]=useState(product.image); const [liked,setLiked]=useState(false); return <main className="product-page"><a className="back-link" href={routeHref('shop')}><ChevronLeft size={17}/> Back to shop</a><div className="product-layout"><div className="product-gallery"><div className="main-image"><img src={image} alt={product.name}/><span className="image-label">{product.label}</span></div><div className="thumbs">{product.thumbs.map((thumb)=><button key={thumb} className={image===thumb?'active':''} onClick={()=>setImage(thumb)}><img src={thumb} alt=""/></button>)}</div></div><div className="product-details"><div className="eyebrow">{product.category} / Available to order</div><div className="detail-title"><h1>{product.name}</h1><button className={liked?'liked like-button':'like-button'} onClick={()=>setLiked(!liked)} aria-label="Save product"><Heart fill={liked?'currentColor':'none'}/></button></div><p className="product-intro">{product.intro}</p><p className="product-description">{product.description}</p><div className="product-price">{money(product.price)} <span>Price in ZAR</span></div><ul className="feature-list">{product.features.map((f)=><li key={f}><CheckCircle2 size={16}/>{f}</li>)}</ul><button className="button button-primary full-button" onClick={onOrder}>Order on WhatsApp <MessageCircle size={17}/></button><div className="order-note"><ShieldCheck size={19}/><div><b>Pay on delivery</b><span>We confirm stock and delivery timing with you before dispatch. Delivery is free in our starting area.</span></div></div><div className="product-accordions"><details open><summary>How this order works <ChevronDown/></summary><p>Complete the short form, then WhatsApp opens with the product and delivery information ready to send.</p></details><details><summary>Looking for something else? <ChevronDown/></summary><p>Send us a product name, link or photo. We’ll check if we can source it and come back with availability and price.</p></details></div><a className="source-link" href={chatUrl(`Hi KwikDrop! I am looking for a product similar to ${product.name}. Can you check if you can source it?`)} target="_blank" rel="noreferrer">Ask us to source a product <ArrowUpRight size={15}/></a></div></div><div className="mobile-order-bar"><button onClick={onOrder}>Order on WhatsApp <MessageCircle size={17}/></button></div></main>; }

function OrderModal({product,onClose}) { const [form,setForm]=useState({name:'',email:'',address:'',suburb:'',notes:''}); const [error,setError]=useState(''); const update=(key,value)=>setForm((old)=>({...old,[key]:value})); const submit=(e)=>{e.preventDefault(); if(!form.name||!form.address||!form.suburb){setError('Please complete your name, delivery address and suburb.');return;} const message=`Hi KwikDrop! I would like to order:\n\nPRODUCT\n${product.name} × 1\nPrice: ${money(product.price)}\n\nCUSTOMER DETAILS\nName: ${form.name}\nEmail: ${form.email||'Not provided'}\nAddress: ${form.address}\nSuburb: ${form.suburb}\nNotes: ${form.notes||'None'}\n\nPlease confirm stock and delivery timing before dispatch. Delivery is free in our starting area.`; window.open(chatUrl(message),'_blank','noopener,noreferrer');onClose();}; return <div className="modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="order-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><div className="eyebrow">One clear message</div><h2>Order {product.name}</h2></div><button onClick={onClose} aria-label="Close order form"><X/></button></div><p className="modal-lede">Add the delivery details and we’ll open WhatsApp with the product information ready to send.</p><form onSubmit={submit}><div className="form-grid"><label>Full name<input value={form.name} onChange={(e)=>update('name',e.target.value)} placeholder="Your name"/></label><label>Email <small>optional</small><input type="email" value={form.email} onChange={(e)=>update('email',e.target.value)} placeholder="you@example.com"/></label><label>Suburb<input value={form.suburb} onChange={(e)=>update('suburb',e.target.value)} placeholder="Umbilo or Glenwood"/></label><label className="full-field">Delivery address<input value={form.address} onChange={(e)=>update('address',e.target.value)} placeholder="Street address, building or house number"/></label><label className="full-field">Delivery notes <small>optional</small><input value={form.notes} onChange={(e)=>update('notes',e.target.value)} placeholder="Gate code, landmark, etc."/></label></div>{error&&<p className="form-error">{error}</p>}<div className="modal-footer"><div><strong>{money(product.price)}</strong><span>Product price · free delivery</span></div><button className="button button-primary" type="submit">Continue to WhatsApp <ArrowRight size={17}/></button></div></form></section></div>; }
