import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, ArrowUpRight, BadgeCheck, ChevronDown, ChevronLeft, Heart, Menu, MessageCircle, Search, ShieldCheck, Truck, X, MapPin, Clock3, CheckCircle2 } from 'lucide-react';

const WHATSAPP_NUMBER = '27821234567';
const money = (value) => `R${value.toLocaleString('en-ZA')}`;
const chatUrl = (message) => `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
const routeHref = (hash='') => `${import.meta.env.BASE_URL}index.html${hash ? `#${hash}` : ''}`;
const categories = ['All products','Tech','Home','Everyday'];
const products = [
  { id:'aroma-diffuser', name:'Halo Mist Diffuser', category:'Home', price:349, label:'Popular pick', intro:'Soft light. Quiet mist. A better-feeling room.', description:'A compact aroma diffuser for bedrooms, living rooms and work spaces. Stock and colour are confirmed with you before delivery.', features:['Quiet mist output','Soft ambient LED light','Compact everyday size'], image:'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1400&q=88', thumbs:['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1400&q=88'] },
  { id:'desk-lamp', name:'Luma Desk Light', category:'Tech', price:289, label:'Workspace', intro:'Focused light for work, study and late nights.', description:'A rechargeable desk light with adjustable brightness for study sessions, bedside tables and focused work.', features:['Multiple brightness modes','USB rechargeable','Adjustable neck'], image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1400&q=88', thumbs:['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=88'] },
  { id:'travel-mug', name:'Everyday Tumbler', category:'Everyday', price:239, label:'Everyday carry', intro:'A cleaner daily carry, from the first sip.', description:'A good-looking insulated tumbler for commutes, campus, errands and car cup holders.', features:['Double-wall insulated','Secure lid','Cup-holder friendly'], image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=88', thumbs:['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1400&q=88'] },
  { id:'carry-organiser', name:'Carry-All Organiser', category:'Everyday', price:199, label:'Daily essential', intro:'The small things, finally in one place.', description:'A slim organiser for cables, chargers, cards and everyday bits. Ask us about the colour currently available.', features:['Multiple compartments','Water-resistant outer','Slim travel profile'], image:'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1400&q=88', thumbs:['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1589363360147-4f2d51541551?auto=format&fit=crop&w=1400&q=88','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=88'] }
];

function Reveal({ children, className='' }) { useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold:.12 }); document.querySelectorAll('.reveal').forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, []); return <div className={`reveal ${className}`}>{children}</div>; }

export default function App() {
  const [route,setRoute] = useState(window.location.hash);
  const [menuOpen,setMenuOpen] = useState(false);
  const [searchOpen,setSearchOpen] = useState(false);
  const [query,setQuery] = useState('');
  const [category,setCategory] = useState('All products');
  const [orderProduct,setOrderProduct] = useState(null);
  useEffect(() => { const handler=()=>setRoute(window.location.hash); window.addEventListener('hashchange',handler); return()=>window.removeEventListener('hashchange',handler); },[]);
  useEffect(() => window.scrollTo({ top:0, behavior:'instant' }),[route]);
  const go = (hash='') => { const next = hash ? `#${hash}` : ''; setMenuOpen(false); setSearchOpen(false); if (window.location.hash === next) { setRoute(next); return; } window.location.assign(`${window.location.pathname}${next}`); };
  const currentProduct = route.startsWith('#product/') ? products.find((p)=>p.id===route.slice(9)) : null;
  const requestedPage = route.slice(1) || 'home';
  const page = currentProduct ? 'product' : (requestedPage.startsWith('product/') ? 'shop' : requestedPage);
  const visibleProducts = useMemo(() => products.filter((p)=>(category==='All products'||p.category===category)&&(!query||`${p.name} ${p.intro} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
  return <div className="app-shell"><div className="announcement"><span className="pulse"/> Free delivery <b>Umbilo + Glenwood</b><span>•</span> Pay when it arrives <ArrowUpRight size={13}/></div><header className="site-header"><button className="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen?<X/>:<Menu/>}</button><a className="brand" href={routeHref('')} aria-label="KwikDrop home"><span>kwik</span><i>drop</i><b>.</b></a><nav className={menuOpen?'nav-links open':'nav-links'}><a href={routeHref('')}>Home</a><a href={routeHref('shop')}>Shop</a><a href={routeHref('how-it-works')}>How it works</a><a href={routeHref('delivery')}>Delivery</a><a href={routeHref('faqs')}>FAQs</a></nav><div className="header-actions"><button className="search-trigger" onClick={()=>setSearchOpen(!searchOpen)} aria-label="Search"><Search size={18}/></button><a className="header-chat" href={chatUrl('Hi KwikDrop! I have a question before ordering.')} target="_blank" rel="noreferrer"><MessageCircle size={17}/><span>WhatsApp us</span></a></div></header>{searchOpen&&<div className="searchbar"><Search size={17}/><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search products"/><button onClick={()=>setSearchOpen(false)} aria-label="Close search"><X size={17}/></button></div>}{page==='home'?<Home go={go}/>:page==='shop'?<Shop items={visibleProducts} category={category} setCategory={setCategory} openProduct={(p)=>go(`product/${p.id}`)}/>:page==='how-it-works'?<InfoPage type="how"/>:page==='delivery'?<InfoPage type="delivery"/>:page==='faqs'?<InfoPage type="faqs"/>:<ProductView product={currentProduct} onOrder={()=>setOrderProduct(currentProduct)}/>}<a className="floating-wa" href={chatUrl('Hi KwikDrop! I would like help choosing a product.')} target="_blank" rel="noreferrer"><MessageCircle size={20}/><span>Chat with us</span></a><footer className="site-footer"><div><a className="brand footer-logo" href={routeHref('')}><span>kwik</span><i>drop</i><b>.</b></a><p>Local products. Straightforward service.</p></div><div className="footer-links"><span>Durban, South Africa</span><span>© 2026 KwikDrop</span><a href={routeHref('shop')}>Shop products <ArrowRight size={14}/></a></div></footer>{orderProduct&&<OrderModal product={orderProduct} onClose={()=>setOrderProduct(null)}/>}</div>;
}

function Home() { return <main className="home-page"><section className="hero-cinematic"><div className="hero-bg"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light"><span className="eyebrow-mark"/> Durban’s find-it-first store</div><h1>Good finds.<br/><em>Right around here.</em></h1><p>Tech, home and everyday products worth knowing about — brought to you locally, with a real person on the other side.</p><div className="hero-actions"><a className="button button-primary" href={routeHref('shop')}>See what’s in store <ArrowRight size={17}/></a><a className="hero-link" href={routeHref('how-it-works')}>How ordering works <ArrowUpRight size={15}/></a></div><div className="hero-proof light"><span><CheckCircle2 size={16}/> Stock checked before delivery</span><span><ShieldCheck size={16}/> Pay when it arrives</span></div></div><div className="hero-product-card"><span>FEATURED NOW</span><strong>Halo Mist Diffuser</strong><small>From {money(349)}</small></div><div className="hero-scroll">Scroll to explore <ArrowDownIcon/></div></section><Reveal><section className="home-intro"><div className="eyebrow">A store that keeps it moving</div><h2>See it. Ask about it.<br/><em>Get it delivered.</em></h2><p>New products come and go. The standard stays the same: clear prices, honest availability and a real conversation before delivery.</p><a className="button button-secondary" href={routeHref('shop')}>See what’s in the shop <ArrowRight size={16}/></a></section></Reveal><Reveal><section className="home-featured"><div className="section-head"><div><div className="eyebrow">A few things in store</div><h2>Start here.</h2></div><a className="under-link" href={routeHref('shop')}>View all products <ArrowUpRight size={15}/></a></div><div className="featured-grid">{products.slice(0,3).map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={(item)=>go(`product/${item.id}`)}/>)}</div></section></Reveal><Reveal><section className="source-banner"><div><div className="eyebrow">Can’t find what you’re after?</div><h2>Send us the product.<br/><em>We’ll check.</em></h2></div><a className="button button-primary" href={chatUrl('Hi KwikDrop! I am looking for a product I saw online. Can you check availability and price?')} target="_blank" rel="noreferrer">Ask us to source it <MessageCircle size={17}/></a></section></Reveal></main>; }

function Shop({items,category,setCategory,openProduct}) { return <main className="shop-page"><section className="catalog catalog-premium catalog-direct"><div className="catalog-topline"><div><span className="catalog-kicker">The KwikDrop shop</span><h2>Pick your lane.</h2></div><span className="catalog-count-large">{items.length} <small>available now</small></span></div><div className="catalog-head"><span><b>{items.length}</b> products <small>• Free delivery • Pay on delivery</small></span><div className="filter-row">{categories.map((item)=><button className={category===item?'active':''} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</div></div><div className="product-grid product-grid-premium">{items.map((p,i)=><ProductCard key={p.id} product={p} index={i} openProduct={openProduct}/>)}</div><div className="shop-bottom-note"><div><span className="eyebrow">Looking for something specific?</span><h3>Send us a screenshot. We’ll check it.</h3></div><a href={chatUrl('Hi KwikDrop! I am looking for a product I saw online. Can you check availability and price?')} target="_blank" rel="noreferrer" className="button button-secondary">Ask us to source it <MessageCircle size={16}/></a></div></section></main>; }

function ProductCard({product,index}) { return <a className="product-card" href={routeHref(`product/${product.id}`)}><div className="product-image"><img src={product.image} alt={product.name} loading={index>1?'lazy':'eager'}/><span>{product.label}</span><span className="card-open" aria-hidden="true"><ArrowUpRight size={18}/></span></div><div className="product-card-info"><div><h3>{product.name}</h3><p>{product.category} · {product.intro}</p></div><strong>{money(product.price)}</strong></div><div className="card-order-hint">See product details <ArrowRight size={14}/></div></a>; }

function InfoPage({type}) { const content={how:{eyebrow:'How it works',title:<>Order without<br/><em>the awkward checkout.</em></>,lead:'You choose the product. We confirm the details with you. Then we bring it over and you pay when it arrives.',cards:[['01','Pick a product','Browse the shop and open anything you want to know more about.'],['02','Send the details','Fill in the short form. WhatsApp opens with one complete order message.'],['03','We confirm','We check stock, your area, the the plan with you. Delivery is free in our starting area.'],['04','Receive and pay','We deliver locally. You pay on delivery.']]},delivery:{eyebrow:'Delivery',title:<>Know where we<br/><em>can bring it.</em></>,lead:'KwikDrop is starting close to home so we can keep the service personal and the communication clear.',cards:[['AREA','Umbilo + Glenwood','This is our initial delivery area in Durban. Nearby suburbs may be possible — ask us before ordering.'],['FEE','Confirmed first','Delivery is free in our starting area. We confirm stock and timing with you on WhatsApp before dispatch.'],['PAY','On delivery','There is no card checkout on the website. You pay when your order arrives.'],['TIME','Arranged together','We agree on a suitable delivery time in the WhatsApp conversation.']]},faqs:{eyebrow:'FAQs',title:<>The useful answers,<br/><em>before you ask.</em></>,lead:'No hidden checkout steps. Free delivery in our starting area.',cards:[['How do I order?','Choose a product, complete the short form and continue to WhatsApp.'],['When do I pay?','When the order arrives. We confirm the product and delivery details first.'],['Can you find another product?','Send us the product name, link or a photo. We’ll check availability and price.'],['Do you deliver outside the starting area?','Message us with your suburb. Nearby delivery may be possible depending on the order.']]}}[type]; return <main className="info-page"><section className="page-hero"><div className="eyebrow"><span className="eyebrow-mark"/> {content.eyebrow}</div><h1>{content.title}</h1><p>{content.lead}</p></section><Reveal><section className={`info-grid ${type==='faqs'?'faq-grid':''}`}>{content.cards.map((card)=><div className="info-card" key={card[0]}>{type==='faqs'?<><h3>{card[0]} <ChevronDown size={17}/></h3><p>{card[1]}</p></>:<><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></>}</div>)}</section></Reveal><div className="info-cta"><h2>Ready to look around?</h2><a className="button button-primary" href={routeHref('shop')}>Go to the shop <ArrowRight size={17}/></a></div></main>; }

function ArrowDownIcon(){return <span className="arrow-down">↓</span>}
function ProductView({product,onOrder}) { const [image,setImage]=useState(product.image); const [liked,setLiked]=useState(false); return <main className="product-page"><a className="back-link" href={routeHref('shop')}><ChevronLeft size={17}/> Back to shop</a><div className="product-layout"><div className="product-gallery"><div className="main-image"><img src={image} alt={product.name}/><span className="image-label">{product.label}</span></div><div className="thumbs">{product.thumbs.map((thumb)=><button key={thumb} className={image===thumb?'active':''} onClick={()=>setImage(thumb)}><img src={thumb} alt=""/></button>)}</div></div><div className="product-details"><div className="eyebrow">{product.category} / Available to order</div><div className="detail-title"><h1>{product.name}</h1><button className={liked?'liked like-button':'like-button'} onClick={()=>setLiked(!liked)} aria-label="Save product"><Heart fill={liked?'currentColor':'none'}/></button></div><p className="product-intro">{product.intro}</p><p className="product-description">{product.description}</p><div className="product-price">{money(product.price)} <span>Price in ZAR</span></div><ul className="feature-list">{product.features.map((f)=><li key={f}><CheckCircle2 size={16}/>{f}</li>)}</ul><button className="button button-primary full-button" onClick={onOrder}>Order on WhatsApp <MessageCircle size={17}/></button><div className="order-note"><ShieldCheck size={19}/><div><b>Pay on delivery</b><span>We confirm stock and delivery timing with you before dispatch. Delivery is free in our starting area.</span></div></div><div className="product-accordions"><details open><summary>How this order works <ChevronDown/></summary><p>Complete the short form, then WhatsApp opens with the product and delivery information ready to send.</p></details><details><summary>Looking for something else? <ChevronDown/></summary><p>Send us a product name, link or photo. We’ll check if we can source it and come back with availability and price.</p></details></div><a className="source-link" href={chatUrl(`Hi KwikDrop! I am looking for a product similar to ${product.name}. Can you check if you can source it?`)} target="_blank" rel="noreferrer">Ask us to source a product <ArrowUpRight size={15}/></a></div></div><div className="mobile-order-bar"><button onClick={onOrder}>Order on WhatsApp <MessageCircle size={17}/></button></div></main>; }

function OrderModal({product,onClose}) { const [form,setForm]=useState({name:'',email:'',address:'',suburb:'',notes:''}); const [error,setError]=useState(''); const update=(key,value)=>setForm((old)=>({...old,[key]:value})); const submit=(e)=>{e.preventDefault(); if(!form.name||!form.address||!form.suburb){setError('Please complete your name, delivery address and suburb.');return;} const message=`Hi KwikDrop! I would like to order:\n\nPRODUCT\n${product.name} × 1\nPrice: ${money(product.price)}\n\nCUSTOMER DETAILS\nName: ${form.name}\nEmail: ${form.email||'Not provided'}\nAddress: ${form.address}\nSuburb: ${form.suburb}\nNotes: ${form.notes||'None'}\n\nPlease confirm stock and delivery timing before dispatch. Delivery is free in our starting area.`; window.open(chatUrl(message),'_blank','noopener,noreferrer');onClose();}; return <div className="modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="order-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><div className="eyebrow">One clear message</div><h2>Order {product.name}</h2></div><button onClick={onClose} aria-label="Close order form"><X/></button></div><p className="modal-lede">Add the delivery details and we’ll open WhatsApp with the product information ready to send.</p><form onSubmit={submit}><div className="form-grid"><label>Full name<input value={form.name} onChange={(e)=>update('name',e.target.value)} placeholder="Your name"/></label><label>Email <small>optional</small><input type="email" value={form.email} onChange={(e)=>update('email',e.target.value)} placeholder="you@example.com"/></label><label>Suburb<input value={form.suburb} onChange={(e)=>update('suburb',e.target.value)} placeholder="Umbilo or Glenwood"/></label><label className="full-field">Delivery address<input value={form.address} onChange={(e)=>update('address',e.target.value)} placeholder="Street address, building or house number"/></label><label className="full-field">Delivery notes <small>optional</small><input value={form.notes} onChange={(e)=>update('notes',e.target.value)} placeholder="Gate code, landmark, etc."/></label></div>{error&&<p className="form-error">{error}</p>}<div className="modal-footer"><div><strong>{money(product.price)}</strong><span>Product price · free delivery</span></div><button className="button button-primary" type="submit">Continue to WhatsApp <ArrowRight size={17}/></button></div></form></section></div>; }
