import { useEffect, useMemo, useState } from 'react';
import {
  ArrowRight, ArrowUpRight, BadgeCheck, ChevronDown, ChevronLeft, Heart, Menu,
  MessageCircle, Minus, Plus, Search, ShieldCheck, Truck, X, MapPin, PackageCheck,
  Clock3, CheckCircle2, CircleHelp, SlidersHorizontal
} from 'lucide-react';

const WHATSAPP_NUMBER = '27821234567';
const AREAS = 'Umbilo + Glenwood';
const products = [
  { id:'aroma-diffuser', name:'Halo Mist Diffuser', category:'Home', price:349, label:'Popular pick', intro:'Soft light. Quiet mist. A better-feeling room.', description:'A compact aroma diffuser for bedrooms, living rooms and work spaces. Stock and colour are confirmed with you before delivery.', features:['Quiet mist output','Soft ambient LED light','Compact everyday size'], image:'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=85', thumbs:['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=85'] },
  { id:'desk-lamp', name:'Luma Desk Light', category:'Home', price:289, label:'Workspace', intro:'Focused light for work, study and late nights.', description:'A rechargeable desk light with adjustable brightness for study sessions, bedside tables and focused work.', features:['Multiple brightness modes','USB rechargeable','Adjustable neck'], image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85', thumbs:['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85'] },
  { id:'travel-mug', name:'Everyday Tumbler', category:'Everyday', price:239, label:'Everyday carry', intro:'A cleaner daily carry, from the first sip.', description:'A good-looking insulated tumbler for commutes, campus, errands and car cup holders.', features:['Double-wall insulated','Secure lid','Cup-holder friendly'], image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85', thumbs:['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=85'] },
  { id:'carry-organiser', name:'Carry-All Organiser', category:'Everyday', price:199, label:'Daily essential', intro:'The small things, finally in one place.', description:'A slim organiser for cables, chargers, cards and everyday bits. Ask us about the colour currently available.', features:['Multiple compartments','Water-resistant outer','Slim travel profile'], image:'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85', thumbs:['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1589363360147-4f2d51541551?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85'] }
];
const categories = ['All products','Home','Everyday'];
const money = (value) => `R${value.toLocaleString('en-ZA')}`;
const chatUrl = (message) => `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;

function Reveal({ children, className='' }) {
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold:.12 });
    document.querySelectorAll('.reveal').forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  return <div className={`reveal ${className}`}>{children}</div>;
}

export default function App() {
  const [route, setRoute] = useState(window.location.hash);
  const [category, setCategory] = useState('All products');
  const [query, setQuery] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [orderProduct, setOrderProduct] = useState(null);
  const [selectedProduct, setSelectedProduct] = useState(null);
  useEffect(() => { const onHash = () => setRoute(window.location.hash); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => { const id = route.startsWith('#product/') ? route.slice(9) : null; setSelectedProduct(products.find((item) => item.id === id) || null); window.scrollTo({ top:0, behavior:'instant' }); }, [route]);
  const visibleProducts = useMemo(() => products.filter((item) => (category === 'All products' || item.category === category) && (!query || `${item.name} ${item.intro} ${item.category}`.toLowerCase().includes(query.toLowerCase()))), [category, query]);
  const go = (hash='') => { window.location.hash = hash; setMenuOpen(false); };
  const jump = (id) => { setMenuOpen(false); if (route) window.location.hash = ''; setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior:'smooth' }), 30); };
  const openProduct = (item) => go(`product/${item.id}`);
  const home = !selectedProduct && route !== '#shop';
  return <div className="app-shell">
    <div className="announcement"><span className="pulse"/> Durban local delivery <b>Umbilo + Glenwood</b><span className="announcement-sep">•</span> Pay when it arrives <ArrowUpRight size={14}/></div>
    <header className="site-header">
      <button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</button>
      <button className="brand" onClick={() => go('')} aria-label="KwikDrop home"><span>kwik</span><i>drop</i><b>.</b></button>
      <nav className={menuOpen ? 'nav-links open' : 'nav-links'}><button onClick={() => go('')}>Home</button><button onClick={() => go('shop')}>Shop</button><button onClick={() => jump('how-it-works')}>How it works</button><button onClick={() => jump('delivery')}>Delivery</button><button onClick={() => jump('faq')}>FAQs</button></nav>
      <div className="header-actions"><button className="search-trigger" onClick={() => setSearchOpen(!searchOpen)} aria-label="Search products"><Search size={18}/></button><a className="header-chat" href={chatUrl('Hi KwikDrop! I have a question before ordering.')} target="_blank" rel="noreferrer"><MessageCircle size={17}/><span>WhatsApp us</span></a></div>
    </header>
    {searchOpen && <div className="searchbar"><Search size={17}/><input autoFocus value={query} onChange={(e) => { setQuery(e.target.value); if (route !== '#shop') go('shop'); }} placeholder="Search products"/><button onClick={() => { setSearchOpen(false); setQuery(''); }} aria-label="Close search"><X size={17}/></button></div>}
    {selectedProduct ? <ProductView product={selectedProduct} onBack={() => go('shop')} onOrder={() => setOrderProduct(selectedProduct)}/> : route === '#shop' ? <ShopView products={visibleProducts} category={category} setCategory={setCategory} openProduct={openProduct}/> : <HomeView goShop={() => go('shop')} jump={jump} openProduct={openProduct}/>} 
    <a className="floating-wa" href={chatUrl('Hi KwikDrop! I would like help choosing a product.')} target="_blank" rel="noreferrer"><MessageCircle size={20}/><span>Chat with us</span></a>
    <footer className="site-footer"><div><button className="brand footer-logo" onClick={() => go('')}><span>kwik</span><i>drop</i><b>.</b></button><p>Local shopping, made simple.</p></div><div className="footer-links"><span>Durban, South Africa</span><span>© 2026 KwikDrop</span><button onClick={() => go('shop')}>Shop products <ArrowRight size={14}/></button></div></footer>
    {orderProduct && <OrderModal product={orderProduct} onClose={() => setOrderProduct(null)}/>} 
  </div>;
}

function HomeView({ goShop, jump, openProduct }) { return <main className="home-page">
  <section className="hero hero-home"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-mark"/> A local online store for Durban</div><h1>Shop online.<br/><em>Order simply.</em></h1><p>Products you can choose from home, with a real person confirming the details on WhatsApp. We deliver locally and you pay when your order arrives.</p><div className="hero-actions"><button className="button button-primary" onClick={goShop}>Browse the shop <ArrowRight size={17}/></button><button className="under-link" onClick={() => jump('how-it-works')}>See how it works <ArrowUpRight size={15}/></button></div><div className="hero-proof"><span><CheckCircle2 size={16}/> Stock confirmed first</span><span><ShieldCheck size={16}/> No online card payment</span></div></div><div className="hero-visual"><div className="visual-backdrop"/><div className="hero-product"><img src={products[0].image} alt="Halo Mist Diffuser"/><div className="product-overlay"><span>FEATURED PRODUCT</span><strong>Halo Mist Diffuser</strong><small>From {money(products[0].price)}</small></div></div><div className="delivery-chip"><Truck size={17}/><span><b>Local delivery</b>Umbilo + Glenwood</span></div><div className="pay-chip"><BadgeCheck size={19}/><span>Pay on delivery</span></div></div></section>
  <section className="trust-bar"><div><Truck/><span><b>Local delivery</b> Starting in Umbilo + Glenwood</span></div><div><MessageCircle/><span><b>WhatsApp confirmation</b> One clear order message</span></div><div><ShieldCheck/><span><b>Pay on delivery</b> No card details required</span></div><div><Clock3/><span><b>Clear communication</b> We confirm timing first</span></div></section>
  <Reveal><section className="intro-panel"><div className="eyebrow">A better way to shop locally</div><h2>Online convenience.<br/><em>Human confirmation.</em></h2><p>KwikDrop brings a straightforward online shopping experience to your neighbourhood. Pick a product, send your details, and chat to a real person before anything is delivered.</p><button className="button button-secondary" onClick={goShop}>View all products <ArrowRight size={16}/></button></section></Reveal>
  <Reveal><section className="featured-section"><div className="section-head"><div><div className="eyebrow">Start with the shop</div><h2>See what’s<br/><em>available.</em></h2></div><button className="under-link" onClick={goShop}>View full shop <ArrowUpRight size={15}/></button></div><div className="featured-grid">{products.slice(0,3).map((item,index) => <ProductCard key={item.id} product={item} index={index} openProduct={openProduct}/>)}</div></section></Reveal>
  <Reveal><section className="how-section" id="how-it-works"><div className="how-copy"><div className="eyebrow">The KwikDrop order flow</div><h2>Simple from<br/><em>start to doorstep.</em></h2><p>No complicated checkout. No paying before you know the details. WhatsApp is where we confirm your product, delivery fee and timing.</p><a className="button button-primary" href={chatUrl('Hi KwikDrop! I need help with an order.')} target="_blank" rel="noreferrer">Ask us anything <MessageCircle size={17}/></a></div><div className="steps-list"><div><span>01</span><div><b>Choose your product</b><p>Browse the shop, see the price and check the details.</p></div></div><div><span>02</span><div><b>Send your order on WhatsApp</b><p>Your name, number and delivery details arrive in one message.</p></div></div><div><span>03</span><div><b>We confirm everything</b><p>We confirm stock, delivery fee and a suitable time with you.</p></div></div><div><span>04</span><div><b>Receive it and pay</b><p>Pay on delivery once your order arrives.</p></div></div></div></section></Reveal>
  <Reveal><section className="delivery-section" id="delivery"><div className="delivery-copy"><div className="eyebrow">Delivery, without the guesswork</div><h2>Local first.<br/><em>Clear always.</em></h2><p>We are starting with focused local delivery so we can keep communication reliable and personal.</p></div><div className="delivery-card"><div className="delivery-card-top"><MapPin size={21}/><span>Current delivery area</span></div><strong>Umbilo + Glenwood</strong><p>Nearby Durban areas may be possible. Send us your suburb and we’ll confirm before dispatch.</p><div className="delivery-card-line"><CheckCircle2 size={16}/> Fee confirmed with you first</div><div className="delivery-card-line"><CheckCircle2 size={16}/> Payment collected on delivery</div></div></section></Reveal>
  <Reveal><section className="faq-section" id="faq"><div className="eyebrow">Questions, answered upfront</div><h2>Before you order.</h2><div className="faq-list"><details open><summary>How do I place an order? <ChevronDown/></summary><p>Choose a product, complete the short customer form and tap the WhatsApp button. We receive one complete message and confirm stock, delivery fee and timing with you.</p></details><details><summary>When do I pay? <ChevronDown/></summary><p>You pay when your order arrives. KwikDrop does not ask you to enter card details on this website.</p></details><details><summary>What if I am outside Umbilo or Glenwood? <ChevronDown/></summary><p>Send us your suburb on WhatsApp. We are starting locally, but nearby delivery may be possible depending on the order.</p></details></div></section></Reveal>
</main>; }

function ShopView({ products:items, category, setCategory, openProduct }) { return <main className="shop-page"><section className="shop-hero"><div className="eyebrow"><span className="eyebrow-mark"/> The KwikDrop shop</div><h1>Products worth<br/><em>making space for.</em></h1><p>Browse the range, choose what you like and send one clear order through WhatsApp. We confirm the rest with you.</p></section><section className="catalog"><div className="catalog-head"><div><span className="catalog-count">{items.length} products</span><span className="catalog-note">• Local delivery • Pay on delivery</span></div><div className="filter-row"><SlidersHorizontal size={16}/>{categories.map((item) => <button key={item} className={category===item?'active':''} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="product-grid">{items.map((item,index) => <ProductCard key={item.id} product={item} index={index} openProduct={openProduct}/>)}</div>{!items.length && <div className="empty-state">No products match that search. <button onClick={() => setCategory('All products')}>Show all products</button></div>}</section></main>; }

function ProductCard({ product, index, openProduct }) { return <article className="product-card" onClick={() => openProduct(product)}><div className="product-image"><img src={product.image} alt={product.name} loading={index>1?'lazy':'eager'}/><span>{product.label}</span><button aria-label={`View ${product.name}`} onClick={(e) => { e.stopPropagation(); openProduct(product); }}><ArrowUpRight size={18}/></button></div><div className="product-card-info"><div><h3>{product.name}</h3><p>{product.category} · {product.intro}</p></div><strong>{money(product.price)}</strong></div><div className="card-order-hint">View product details <ArrowRight size={14}/></div></article>; }

function ProductView({ product, onBack, onOrder }) { const [image,setImage] = useState(product.image); const [liked,setLiked] = useState(false); return <main className="product-page"><button className="back-link" onClick={onBack}><ChevronLeft size={17}/> Back to shop</button><div className="product-layout"><div className="product-gallery"><div className="main-image"><img src={image} alt={product.name}/><span className="image-label">{product.label}</span></div><div className="thumbs">{product.thumbs.map((thumb) => <button key={thumb} className={image===thumb?'active':''} onClick={() => setImage(thumb)}><img src={thumb} alt=""/></button>)}</div></div><div className="product-details"><div className="eyebrow">{product.category} / Available to order</div><div className="detail-title"><h1>{product.name}</h1><button className={liked?'liked like-button':'like-button'} onClick={() => setLiked(!liked)} aria-label="Save product"><Heart fill={liked?'currentColor':'none'}/></button></div><p className="product-intro">{product.intro}</p><p className="product-description">{product.description}</p><div className="product-price">{money(product.price)} <span>Price in ZAR</span></div><ul className="feature-list">{product.features.map((feature) => <li key={feature}><CheckCircle2 size={16}/>{feature}</li>)}</ul><button className="button button-primary full-button" onClick={onOrder}>Order on WhatsApp <MessageCircle size={17}/></button><div className="order-note"><ShieldCheck size={19}/><div><b>Pay on delivery</b><span>We confirm stock, delivery fee and timing with you before dispatch.</span></div></div><div className="product-accordions"><details open><summary>How this order works <ChevronDown/></summary><p>Complete the short order form, then WhatsApp opens with one complete message. We confirm the details personally before delivering.</p></details><details><summary>Delivery area <ChevronDown/></summary><p>Our starting delivery area is Umbilo and Glenwood. Message us with your suburb if you are nearby.</p></details><details><summary>Looking for something else? <ChevronDown/></summary><p>Send us a photo or product name on WhatsApp. We’ll check whether we can source it and come back with availability and price.</p></details></div><a className="source-link" href={chatUrl(`Hi KwikDrop! I am looking for a product similar to ${product.name}. Can you check if you can source it?`)} target="_blank" rel="noreferrer">Ask us to source a product <ArrowUpRight size={15}/></a></div></div><div className="mobile-order-bar"><button onClick={onOrder}>Order on WhatsApp <MessageCircle size={17}/></button></div></main>; }

function OrderModal({ product, onClose }) { const [form,setForm] = useState({ name:'', email:'', address:'', suburb:'', notes:'' }); const [error,setError] = useState(''); const update = (key,value) => setForm((current) => ({...current,[key]:value})); const submit = (e) => { e.preventDefault(); if (!form.name || !form.address || !form.suburb) { setError('Please complete your name, delivery address and suburb.'); return; } const message = `Hi KwikDrop! I would like to order:\n\nPRODUCT\n${product.name} × 1\nPrice: ${money(product.price)}\n\nCUSTOMER DETAILS\nName: ${form.name}\nEmail: ${form.email || 'Not provided'}\nAddress: ${form.address}\nSuburb: ${form.suburb}\nNotes: ${form.notes || 'None'}\n\nPlease confirm stock, delivery fee and timing before dispatch.`; window.open(chatUrl(message), '_blank', 'noopener,noreferrer'); onClose(); }; return <div className="modal-backdrop" onMouseDown={(e) => e.target===e.currentTarget && onClose()}><section className="order-modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><div className="modal-head"><div><div className="eyebrow">One clear message</div><h2 id="order-title">Order {product.name}</h2></div><button onClick={onClose} aria-label="Close order form"><X/></button></div><p className="modal-lede">Add the delivery details and we’ll open WhatsApp with the product information ready to send. We’ll arrange contact and timing in the chat.</p><form onSubmit={submit}><div className="form-grid"><label>Full name<input value={form.name} onChange={(e) => update('name',e.target.value)} placeholder="Your name"/></label><label>Email <small>optional</small><input value={form.email} onChange={(e) => update('email',e.target.value)} placeholder="you@example.com" type="email"/></label><label>Suburb<input value={form.suburb} onChange={(e) => update('suburb',e.target.value)} placeholder="Umbilo or Glenwood"/></label><label className="full-field">Delivery address<input value={form.address} onChange={(e) => update('address',e.target.value)} placeholder="Street address, building or house number"/></label><label className="full-field">Delivery notes <small>optional</small><input value={form.notes} onChange={(e) => update('notes',e.target.value)} placeholder="Gate code, landmark, etc."/></label></div>{error && <p className="form-error">{error}</p>}<div className="modal-footer"><div><strong>{money(product.price)}</strong><span>Product price · delivery fee confirmed on WhatsApp</span></div><button className="button button-primary" type="submit">Continue to WhatsApp <ArrowRight size={17}/></button></div></form></section></div>; }
